//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballStats.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasketballStats.WebApi.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinmeyen bir hata oluştu.
        /// </summary>
        internal static string AnUnkonwnErrorHasOccured {
            get {
                return ResourceManager.GetString("AnUnkonwnErrorHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kamera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kamera markası.
        /// </summary>
        internal static string CameraBrand {
            get {
                return ResourceManager.GetString("CameraBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kamera modeli.
        /// </summary>
        internal static string CameraModel {
            get {
                return ResourceManager.GetString("CameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to istemci uygulaması.
        /// </summary>
        internal static string ClientApplication {
            get {
                return ResourceManager.GetString("ClientApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to istemci uygulama kodu.
        /// </summary>
        internal static string clientapplicationcode {
            get {
                return ResourceManager.GetString("clientapplicationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama kimlik doğrulama hatası.
        /// </summary>
        internal static string ClientApplicationLoginError {
            get {
                return ResourceManager.GetString("ClientApplicationLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to istemci uygulama ismi.
        /// </summary>
        internal static string clientapplicationname {
            get {
                return ResourceManager.GetString("clientapplicationname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekil olan alan için çoklu kayıt hatası.
        /// </summary>
        internal static string DuplicateRecordForUniqueValueError {
            get {
                return ResourceManager.GetString("DuplicateRecordForUniqueValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-posta.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kimlik numarası.
        /// </summary>
        internal static string identitynumber {
            get {
                return ResourceManager.GetString("identitynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik doğrulama hatası.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isim.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu değere ait bir kayıt bulunamadı :.
        /// </summary>
        internal static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bildirim.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bildirim yetkisi.
        /// </summary>
        internal static string NotificationAuthorization {
            get {
                return ResourceManager.GetString("NotificationAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kişi.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fotoğraf URL.
        /// </summary>
        internal static string photourl {
            get {
                return ResourceManager.GetString("photourl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to özellik.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to özellik yetkisi.
        /// </summary>
        internal static string PropertyAuthorization {
            get {
                return ResourceManager.GetString("PropertyAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to özellik ismi.
        /// </summary>
        internal static string propertyname {
            get {
                return ResourceManager.GetString("propertyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seri numarası.
        /// </summary>
        internal static string serialnumber {
            get {
                return ResourceManager.GetString("serialnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunucu.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunucu ismi.
        /// </summary>
        internal static string servername {
            get {
                return ResourceManager.GetString("servername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla tamamlandı.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu erişim için yetki bulunmamakta.
        /// </summary>
        internal static string UnauthorizedAccessError {
            get {
                return ResourceManager.GetString("UnauthorizedAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanıcı.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanıcı grubu.
        /// </summary>
        internal static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanıcı grup ismi.
        /// </summary>
        internal static string usergroupname {
            get {
                return ResourceManager.GetString("usergroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanıcı adı.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
